### PR TITLE
move EmptyDataError to pandas.errors

### PR DESCRIPTION
**Pull request by jameslz**

### CODE REVIEW

**Comment by kbessonov1984** [comment]
Hi James. I had corrected this issues in branch v1.1.2 working towards next release. Now SISTR should be compatible with newest pandas version. I will merge your fix for the time being as next SISTR release 1.1.2 might take longer to release

**Comment by kbessonov1984** [comment]
@aaron and @jrober84 please let me know if you have any objections with this merge. I do not see any issues as fixed the same problem in branch `v1.1.2`. This fix will make SISTR compatible with `pandas >= 1.0.5` similar to the issues we seen in MOB-Suite, ECTyper and others.

**Comment by peterk87** [comment]
@kbessonov1984 One suggestion would be wrap the import of this error with `try/except`:

```python
try:
    from pandas.errors import EmptyDataError
except ImportError:
    from pandas.io.common import EmptyDataError
```

So `sistr_cmd` can work with both previous and current versions of Pandas.

**Comment by kbessonov1984** [comment]
Thank you Peter, I've checked pandas 0.25.3 version and there also `EmptyDataError` is located in `pandas.errors` module. Until pandas version 1.0.5 inclusive the  `EmptyDataError` exception implementation was in two locations `pandas.errors` and `pandas.io.common`, but then they left definition only the `pandas.errors` module. Thus I think if we import from `pandas.errors` than this will make code compatible with all pandas versions ... I will confirm by testing code in the oldest and newest pandas versions.

**Comment by peterk87** [comment]
Thanks @kbessonov1984 that's good to know!

**Comment by kbessonov1984** [comment]
Confirmed, was able to import `EmptyDataError` from `pandas.errors` module even on pandas 0.25.3 old version. Merging to master. Thanks to @jameslz

**Pull request merged**
